            - name: RegEx Issue Labeler
  uses: github/issue-labeler@v3.3
  with:
    # The GITHUB_TOKEN secret
    repo-token: # optional, default is ${{ github.token }}
    # The path to the label configuration file. If the file doesn't exist at the specified path on the runner, action will read from the source repository via the Github API.
    configuration-path: 
    # Controls if versioned regex templates are being used
    enable-versioned-regex: 
    # The regex version number to use. Only required if using versioned regex files
    versioned-regex: # optional
    # Is optional and will result in any issues prior to this timestamp to be ignored
    not-before: # optional
    # The name of the label that should be added to an issue where the specified `version-regex` can not be found.
    body-missing-regex-label: # optional
    # Include the title in the regex target
    include-title: # optional, default is 0
    # Include the body in the regex target
    include-body: # optional, default is 1
    # Remove the label from the issue if the label regex does not match
    sync-labels: # optional, default is 0
    # The number of the issue/PR to label
    issue-number: # optional, default is ${{ github.event.issue.number || github.event.pull_request.number }}
          
